definitions:
  model.Category:
    properties:
      id:
        description: 'example: 1'
        type: integer
      name:
        description: 'example: Groceries'
        type: string
      user_id:
        description: 'example: 1'
        type: integer
    type: object
  model.Transaction:
    properties:
      amount:
        description: 'example: 100.50'
        type: number
      date:
        description: 'example: 2024-01-15T14:30:00Z'
        type: string
      description:
        description: 'example: Payment for services'
        type: string
      id:
        description: 'example: 1'
        type: integer
      type:
        allOf:
        - $ref: '#/definitions/model.TransactionType'
        description: 'example: expense'
      user_id:
        description: 'example: 1'
        type: integer
    type: object
  model.TransactionType:
    enum:
    - expense
    - income
    type: string
    x-enum-varnames:
    - Expense
    - Income
  model.User:
    properties:
      bio:
        description: 'example: Just a regular user.'
        type: string
      email:
        description: 'example: foo@bar.com'
        type: string
      id:
        description: 'example: 1'
        type: integer
      username:
        description: 'example: johndoe'
        type: string
    type: object
info:
  contact: {}
paths:
  /category:
    get:
      description: Returns a list of categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Category'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List categories
      tags:
      - category
    post:
      description: Post an category
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Post categories
      tags:
      - category
  /transaction:
    get:
      description: Returns a list of transactions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Transaction'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List transactions
      tags:
      - transaction
    post:
      description: Create a transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Transaction'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create transaction
      tags:
      - transaction
  /user:
    get:
      description: Returns a list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List users
      tags:
      - user
    post:
      description: Post an user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Post users
      tags:
      - user
swagger: "2.0"
